services:
  frontend:
    image: johnnyip/search-frontend:latest
    ports:
      - "80:3000"

  backend-java:
    image: johnnyip/search-backend-java:latest
    ports:
      - "8080:8080"

  backend-python:
    image: johnnyip/search-backend-python:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
