services:
  frontend:
    image: unclechuen/search-frontend:latest
    ports:
      - "80:3000"
  
  backend-java:
    image: unclechuen/search-backend-java:latest
    ports:
      - "8080:8080"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      