services:
  frontend:
    image: unclechuen/search-frontend:latest
    ports:
      - "80:3000"
  
  backend-java:
    image: unclechuen/search-backend-java:latest
    ports:
      - "8080:8080"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

